name: Tests and schema checks

on:
  pull_request:
    branches: [main]
  workflow_call:
    secrets:
      APOLLO_GRAPH_REF:
        required: false
      APOLLO_KEY:
        required: false
      SUBGRAPH_NAME:
        required: false

env:
  APOLLO_KEY: ${{ secrets.APOLLO_KEY }}

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/test.yml

  check-schema:
    needs: [tests]
    name: Check schema with Apollo Studio
    runs-on: ubuntu-latest
    environment: apollo
    steps:
      - uses: actions/checkout@v3
      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/latest | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH
      - name: Check new schema with Apollo Studio
        run: |
          rover subgraph check ${{ env.APOLLO_GRAPH_REF }} --schema ./api/schema.graphql --name ${{ env.SUBGRAPH_NAME }}
